name: buildUnity
on: 
  push:
    branches:
    - UnityBuildUploader
  workflow_dispatch:
env:
  itchio_project: acaciesong/tick-and-stitch

jobs:
  build:
  strategy:
      matrix:
        include:
          - targetPlatform: StandaloneWindows64
            itchio_channel: Win64
          - targetPlatform: WebGL
            itchio_channel: html5
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: Library
        key: Library-GMTK26-${{ matrix.targetPlatform }}
        restore-keys: |
          Library-GMTK26-
          Library-
    - uses: actions/cache@v4
      with:
        path: |
          Library
          ~/.cache/unity3d
        key: UnityCache-${{ matrix.targetPlatform }}-${{ hashFiles('Packages/packages-lock.json') }}
        restore-keys: |
          UnityCache-${{ matrix.targetPlatform }}-
    - uses: game-ci/unity-builder@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: .
        targetPlatform: ${{ matrix.targetPlatform }}
  
    - uses: actions/upload-artifact@v4
      with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
    - uses: robpc/itchio-upload-action@v1
      with:
        path: build/
        project: ${{ env.itchio_project }}
        channel: ${{ matrix.itchio_channel }}
        api-key: ${{ secrets.ITCHIO_API_KEY }}

    
